Repository AY2223S2-CS2113-T11-3/tp, pull requests merged in 2023-03, with the labels that each got.

#20 Add Scanner to Main and Fix CommandParser
  src/main/java/seedu/pettracker/Main.java
  src/main/java/seedu/pettracker/commands/InvalidCommand.java
  src/main/java/seedu/pettracker/parser/CommandParser.java
  text-ui-test/input.txt
Labels: type.Task, priority.High

#23 Add basic JUnit tests for command parser
  src/test/java/seedu/pettracker/parser/CommandParserTest.java
Labels: type.Task, priority.Medium

#25 Add JUnit test for ExitCommand
  src/test/java/seedu/pettracker/commands/ExitCommandTest.java
Labels: type.Task, priority.Medium

#26 Add Pet class
  src/main/java/seedu/pettracker/data/Pet.java
  src/test/java/seedu/pettracker/data/PetTest.java
Labels: type.Task, priority.High

#35 Debug and Finalize v1.0
  src/main/java/seedu/pettracker/Main.java
  src/main/java/seedu/pettracker/commands/AddPetCommand.java
  src/main/java/seedu/pettracker/commands/AddStatCommand.java
  src/main/java/seedu/pettracker/commands/ExitCommand.java
  src/main/java/seedu/pettracker/commands/ListPetCommand.java
  src/main/java/seedu/pettracker/commands/RemovePetCommand.java
  src/main/java/seedu/pettracker/commands/RemoveStatCommand.java
  src/main/java/seedu/pettracker/data/Pet.java
  src/main/java/seedu/pettracker/data/PetList.java
  src/main/java/seedu/pettracker/parser/CommandParser.java
  src/test/java/seedu/pettracker/data/PetListTest.java
  src/test/java/seedu/pettracker/ui/UiTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, type.Task, priority.High

#38 Create a User Guide
  docs/UserGuide.md
  src/test/java/seedu/pettracker/commands/ExitCommandTest.java
Labels: type.Task, priority.Medium

#39 Add basic assertions
  src/main/java/seedu/pettracker/parser/CommandParser.java
Labels: type.Task, priority.Medium

#40 Add basic logger
  src/main/java/seedu/pettracker/parser/CommandParser.java
Labels: type.Task, priority.Medium

#41 Add Assertion checks for Pet class and Logger for main
  src/main/java/seedu/pettracker/Main.java
  src/main/java/seedu/pettracker/data/Pet.java
Labels: severity.Low

#42 Add more assertions & logging to Pet class
  src/main/java/seedu/pettracker/data/Pet.java
Labels: type.Task, priority.Medium

#43 Add assertion and logging for removing pet from list
  src/main/java/seedu/pettracker/data/PetList.java
Labels: type.Task, priority.Medium

#57 Add basic Task adding methods
  src/main/java/seedu/pettracker/commands/AddTaskCommand.java
  src/main/java/seedu/pettracker/data/Task.java
  src/main/java/seedu/pettracker/data/TaskList.java
  src/main/java/seedu/pettracker/parser/CommandParser.java
  src/main/java/seedu/pettracker/ui/Ui.java
Labels: type.Story, priority.Medium

#58 Add basic task removng methods
  src/main/java/seedu/pettracker/commands/RemoveTaskCommand.java
  src/main/java/seedu/pettracker/data/TaskList.java
  src/main/java/seedu/pettracker/parser/CommandParser.java
  src/main/java/seedu/pettracker/ui/Ui.java
Labels: type.Story, priority.Medium

#59 Add task list viewing methods
  src/main/java/seedu/pettracker/commands/ListTasksCommand.java
  src/main/java/seedu/pettracker/data/TaskList.java
  src/main/java/seedu/pettracker/parser/CommandParser.java
  src/main/java/seedu/pettracker/ui/Ui.java
Labels: type.Story, priority.Medium

#60 Add task marking method
  src/main/java/seedu/pettracker/commands/MarkTaskCommand.java
  src/main/java/seedu/pettracker/data/TaskList.java
  src/main/java/seedu/pettracker/parser/CommandParser.java
  src/main/java/seedu/pettracker/ui/Ui.java
Labels: type.Story, priority.Medium

#63 Add ExitCommand Implementation into DG
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/ExitCommand.puml
  docs/diagrams/Style.puml
  docs/images/ExitCommandSequenceDiagram.png
  src/main/java/seedu/pettracker/Main.java
Labels: type.Task, priority.Medium

#64 Add basic architecture documentation
  docs/DeveloperGuide.md
  docs/_config.yml
  docs/diagrams/ArchitectureDiagram.puml
  docs/images/ArchitectureDiagram.png
Labels: type.Task

#65 Add more CommandParser JUnit Tests
  src/main/java/seedu/pettracker/parser/CommandParser.java
  src/test/java/seedu/pettracker/parser/CommandParserTest.java
Labels: type.Task, priority.Medium

#66 Add ListPetCommand Implementation into DG
  docs/DeveloperGuide.md
  docs/diagrams/ListPetCommand.puml
  docs/images/ListPetCommand.png
  docs/team/grace.md
Labels: type.Task, priority.Medium

#67 Implement edit stat command
  src/main/java/seedu/pettracker/commands/EditStatCommand.java
  src/main/java/seedu/pettracker/data/Pet.java
  src/main/java/seedu/pettracker/data/PetList.java
  src/main/java/seedu/pettracker/parser/CommandParser.java
  src/main/java/seedu/pettracker/ui/Ui.java
Labels: type.Story, priority.Medium

#68 Add Add Pet Stat Feature Implementation into DG
  docs/DeveloperGuide.md
  docs/diagrams/AddPetStatFeature.pptx
  docs/images/AddPetStatFeatureClassDiagram.png
  docs/images/AddPetStatFeatureObjectDiagram (1).png
  docs/images/AddPetStatFeatureObjectDiagram (2).png
Labels: type.Task, priority.Medium

#73 Add saving of pet list to storage
  src/main/java/seedu/pettracker/Main.java
  src/main/java/seedu/pettracker/commands/AddPetCommand.java
  src/main/java/seedu/pettracker/commands/AddStatCommand.java
  src/main/java/seedu/pettracker/commands/AddTaskCommand.java
  src/main/java/seedu/pettracker/commands/Command.java
  src/main/java/seedu/pettracker/commands/EditStatCommand.java
  src/main/java/seedu/pettracker/commands/EditTaskCommand.java
  src/main/java/seedu/pettracker/commands/ExitCommand.java
  src/main/java/seedu/pettracker/commands/InvalidCommand.java
  src/main/java/seedu/pettracker/commands/ListPetCommand.java
  src/main/java/seedu/pettracker/commands/ListTasksCommand.java
  src/main/java/seedu/pettracker/commands/MarkTaskCommand.java
  src/main/java/seedu/pettracker/commands/RemovePetCommand.java
  src/main/java/seedu/pettracker/commands/RemoveStatCommand.java
  src/main/java/seedu/pettracker/commands/RemoveTaskCommand.java
  src/main/java/seedu/pettracker/commands/UnMarkTaskCommand.java
  src/main/java/seedu/pettracker/data/Pet.java
  src/main/java/seedu/pettracker/data/PetList.java
  src/main/java/seedu/pettracker/storage/Storage.java
  src/main/java/seedu/pettracker/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#74 Add saving of task list to storage
  src/main/java/seedu/pettracker/Main.java
  src/main/java/seedu/pettracker/commands/AddTaskCommand.java
  src/main/java/seedu/pettracker/commands/EditTaskCommand.java
  src/main/java/seedu/pettracker/commands/MarkTaskCommand.java
  src/main/java/seedu/pettracker/commands/RemoveTaskCommand.java
  src/main/java/seedu/pettracker/commands/UnMarkTaskCommand.java
  src/main/java/seedu/pettracker/data/Task.java
  src/main/java/seedu/pettracker/data/TaskList.java
  src/main/java/seedu/pettracker/storage/Storage.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#75 Add user stories to DG and update figure numbers
  docs/DeveloperGuide.md
Labels: type.Story, type.Task, priority.Medium

#76 Add loading of pet list from storage
  src/main/java/seedu/pettracker/Main.java
  src/main/java/seedu/pettracker/storage/Storage.java
Labels: type.Story, priority.High

#78 Add loading of task list from storage
  src/main/java/seedu/pettracker/Main.java
  src/main/java/seedu/pettracker/data/TaskList.java
  src/main/java/seedu/pettracker/storage/Storage.java
Labels: type.Story, priority.High

#79 Richard date parsing
  docs/UserGuide.md
  src/main/java/seedu/pettracker/commands/AddTaskCommand.java
  src/main/java/seedu/pettracker/data/Task.java
  src/main/java/seedu/pettracker/data/TaskList.java
Labels: type.Task, priority.Medium

#81 Update user guide to include edit pet stat feature
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#82 Implement reminders and update UG
  docs/UserGuide.md
  output/petoutput.txt
  output/taskoutput.txt
  src/main/java/seedu/pettracker/Main.java
  src/main/java/seedu/pettracker/data/TaskList.java
Labels: type.Story, type.Task, priority.Medium

#87 Add deadline to storage and fix minor reminder bug
  src/main/java/seedu/pettracker/data/Task.java
  src/main/java/seedu/pettracker/data/TaskList.java
  src/main/java/seedu/pettracker/storage/Storage.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, severity.Medium
