Repository AY2223S2-CS2113-T11-3/tp, pull requests merged in 2023-04, with the labels that each got.

#172 Fix Bugs provided in PE Dry run
  docs/UserGuide.md
  src/main/java/seedu/pettracker/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.High, severity.High

#173 Fix stat related bugs
  src/main/java/seedu/pettracker/commands/AddStatCommand.java
  src/main/java/seedu/pettracker/commands/EditStatCommand.java
  src/main/java/seedu/pettracker/commands/RemoveStatCommand.java
  src/main/java/seedu/pettracker/data/Pet.java
  src/main/java/seedu/pettracker/data/PetList.java
  src/main/java/seedu/pettracker/exceptions/InvalidStatException.java
  src/main/java/seedu/pettracker/exceptions/NonPositiveIntegerException.java
  src/main/java/seedu/pettracker/exceptions/PetNotFoundException.java
  src/main/java/seedu/pettracker/storage/Storage.java
  src/main/java/seedu/pettracker/ui/Ui.java
  src/test/java/seedu/pettracker/data/PetTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, priority.High, severity.Medium

#174 Fix empty pet name bug, deleting non existent pets, duplicated pet name
  docs/UserGuide.md
  src/main/java/seedu/pettracker/commands/AddPetCommand.java
  src/main/java/seedu/pettracker/commands/RemovePetCommand.java
  src/main/java/seedu/pettracker/data/PetList.java
  src/main/java/seedu/pettracker/exceptions/DuplicatePetException.java
  src/main/java/seedu/pettracker/exceptions/EmptyPetNameException.java
  src/main/java/seedu/pettracker/storage/Storage.java
  src/main/java/seedu/pettracker/ui/Ui.java
  src/test/java/seedu/pettracker/data/PetListTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, priority.High, severity.High

#175 Update DG to include Product Scope, NFR, Glossary and Manual Testing
  docs/DeveloperGuide.md
  docs/images/ExitCommandSequenceDiagram.png
Labels: type.Task, priority.High

#176 Added TOC and changed wrong header value
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#180 Richard code review
  .gitignore
  src/main/java/seedu/pettracker/commands/AddPetCommand.java
  src/main/java/seedu/pettracker/commands/AddStatCommand.java
  src/main/java/seedu/pettracker/commands/AddTaskCommand.java
  src/main/java/seedu/pettracker/commands/Command.java
  src/main/java/seedu/pettracker/commands/EditStatCommand.java
  src/main/java/seedu/pettracker/commands/EditTaskCommand.java
  src/main/java/seedu/pettracker/commands/ExitCommand.java
  src/main/java/seedu/pettracker/commands/HelpCommand.java
  src/main/java/seedu/pettracker/commands/InvalidCommand.java
  src/main/java/seedu/pettracker/commands/ListPetCommand.java
  src/main/java/seedu/pettracker/commands/ListTasksCommand.java
  src/main/java/seedu/pettracker/commands/MarkTaskCommand.java
  src/main/java/seedu/pettracker/commands/RemovePetCommand.java
  src/main/java/seedu/pettracker/commands/RemoveStatCommand.java
  src/main/java/seedu/pettracker/commands/RemoveTaskCommand.java
  src/main/java/seedu/pettracker/commands/ScheduleCommand.java
  src/main/java/seedu/pettracker/commands/UnMarkTaskCommand.java
  src/main/java/seedu/pettracker/exceptions/EmptyArgException.java
  src/main/java/seedu/pettracker/exceptions/EmptyPetNameException.java
  src/main/java/seedu/pettracker/exceptions/EmptyStatException.java
  src/main/java/seedu/pettracker/exceptions/IllegalArgException.java
  src/main/java/seedu/pettracker/exceptions/UnknownKeywordException.java
  src/main/java/seedu/pettracker/parser/AddPetParser.java
  src/main/java/seedu/pettracker/parser/AddStatParser.java
  src/main/java/seedu/pettracker/parser/AddTaskParser.java
  src/main/java/seedu/pettracker/parser/ArgParser.java
  src/main/java/seedu/pettracker/parser/CommandParser.java
  src/main/java/seedu/pettracker/parser/EditStatParser.java
  src/main/java/seedu/pettracker/parser/EditTaskParser.java
  src/main/java/seedu/pettracker/parser/MarkTaskParser.java
  src/main/java/seedu/pettracker/parser/RemovePetParser.java
  src/main/java/seedu/pettracker/parser/RemoveStatParser.java
  src/main/java/seedu/pettracker/parser/RemoveTaskParser.java
  src/main/java/seedu/pettracker/parser/UnMarkTaskParser.java
  src/test/java/seedu/pettracker/parser/CommandParserTest.java
Labels: type.Task, priority.Medium

#181 Update UG to include new features and updated FAQ
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#182 Add JUnit for Pet & PetList, add TOC to UG
  docs/UserGuide.md
  src/main/java/seedu/pettracker/exceptions/DuplicatePetException.java
  src/main/java/seedu/pettracker/exceptions/InvalidStatException.java
  src/main/java/seedu/pettracker/exceptions/NonPositiveIntegerException.java
  src/main/java/seedu/pettracker/exceptions/PetNotFoundException.java
  src/test/java/seedu/pettracker/data/PetListTest.java
  src/test/java/seedu/pettracker/data/PetTest.java
Labels: type.Task, priority.Medium

#191 Add Ui Class Diagram to DG, more JUnit
  docs/DeveloperGuide.md
  docs/diagrams/Style.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/pettracker/ui/Ui.java
  src/test/java/seedu/pettracker/data/PetListTest.java
Labels: type.Task, priority.Medium

#195 Add Shawn's PPP & update readme.md
  docs/README.md
  docs/team/shawntang.md
Labels: type.Task

#197 Rename shawntang.md to shawntangy.md, changed format of PPP
  docs/AboutUs.md
  docs/team/shawntangy.md
Labels: type.Task, priority.Medium

#194 Add more exception handling to storage
  src/main/java/seedu/pettracker/exceptions/EmptyTaskNameException.java
  src/main/java/seedu/pettracker/exceptions/InvalidMarkTaskSymbolException.java
  src/main/java/seedu/pettracker/exceptions/InvalidSeparatorException.java
  src/main/java/seedu/pettracker/storage/Storage.java
  src/main/java/seedu/pettracker/ui/Ui.java
Labels: type.Task, priority.High, severity.Medium

#193 Update UI and catch null inputs/trailing arguments
  docs/AboutUs.md
  docs/team/grace.md
  docs/team/gracezhuxy.md
  src/main/java/seedu/pettracker/commands/AddTaskCommand.java
  src/main/java/seedu/pettracker/data/Pet.java
  src/main/java/seedu/pettracker/data/PetList.java
  src/main/java/seedu/pettracker/data/TaskList.java
  src/main/java/seedu/pettracker/parser/CommandParser.java
  src/main/java/seedu/pettracker/parser/ListPetParser.java
  src/main/java/seedu/pettracker/storage/Storage.java
  src/main/java/seedu/pettracker/ui/Ui.java
  src/test/java/seedu/pettracker/parser/CommandParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/output/petoutput.txt
  text-ui-test/output/taskoutput.txt
Labels: type.Task, priority.Medium

#212 Fix and improve codes based on code review given by TA
  src/main/java/seedu/pettracker/commands/AddPetCommand.java
  src/main/java/seedu/pettracker/commands/AddStatCommand.java
  src/main/java/seedu/pettracker/commands/AddTaskCommand.java
  src/main/java/seedu/pettracker/commands/EditStatCommand.java
  src/main/java/seedu/pettracker/commands/EditTaskCommand.java
  src/main/java/seedu/pettracker/commands/RemovePetCommand.java
  src/main/java/seedu/pettracker/commands/RemoveStatCommand.java
  src/main/java/seedu/pettracker/data/TaskList.java
  src/main/java/seedu/pettracker/storage/Storage.java
  src/main/java/seedu/pettracker/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#213 Update DG with new class and object diagrams for add pet stat feature using PlantUML
  docs/DeveloperGuide.md
  docs/diagrams/AddPetStatFeature.pptx
  docs/diagrams/AddStatClassDiagram.puml
  docs/diagrams/AddStatObjectDiagramAfter.puml
  docs/diagrams/AddStatObjectDiagramInitial.puml
  docs/images/AddPetStatFeatureClassDiagram.png
  docs/images/AddPetStatFeatureObjectDiagram (1).png
  docs/images/AddPetStatFeatureObjectDiagram (2).png
  docs/images/AddStatClassDiagram.png
  docs/images/AddStatObjectDiagramAfter.png
  docs/images/AddStatObjectDiagramInitial.png
Labels: type.Task, priority.Medium

#214 Update DG/UG Hyperlink and small changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ListPetCommand(1).png
  docs/images/ListPetCommand.png
Labels: type.Task, priority.Medium

#215 Update PPP
  docs/team/pyongjie.md
Labels: type.Task, priority.High

#218 Check for completion or incompletion of tasks
  src/main/java/seedu/pettracker/commands/MarkTaskCommand.java
  src/main/java/seedu/pettracker/commands/UnMarkTaskCommand.java
  src/main/java/seedu/pettracker/data/TaskList.java
  src/main/java/seedu/pettracker/exceptions/TaskAlreadyCompleteException.java
  src/main/java/seedu/pettracker/exceptions/TaskAlreadyIncompleteException.java
  src/main/java/seedu/pettracker/ui/Ui.java
Labels: type.Enhancement

#219 Update PPP again
  docs/team/pyongjie.md
Labels: type.Task, priority.High

#220 Update UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#221 Update PPP again
  docs/team/pyongjie.md
Labels: type.Task, priority.High

#224 Fix final bugs
  src/main/java/seedu/pettracker/commands/AddStatCommand.java
  src/main/java/seedu/pettracker/commands/EditStatCommand.java
  src/main/java/seedu/pettracker/data/PetList.java
  src/main/java/seedu/pettracker/exceptions/InvalidStatValueException.java
  src/main/java/seedu/pettracker/parser/AddStatParser.java
  src/main/java/seedu/pettracker/parser/EditStatParser.java
  src/main/java/seedu/pettracker/storage/Storage.java
  src/main/java/seedu/pettracker/ui/Ui.java
  src/test/java/seedu/pettracker/data/PetListTest.java
Labels: type.Bug, severity.High
